services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    T3\Min\:
        resource: '../Classes/*'

    T3\Min\Minifier:
        public: false

    T3\Min\EventListener\AssetRendererEventListener:
        tags:
            -   name: event.listener
                identifier: 'ext-min-css'
                event: TYPO3\CMS\Core\Page\Event\BeforeStylesheetsRenderingEvent
                method: beforeStyleSheetsRendering
            -   name: event.listener
                identifier: 'ext-min-js'
                event: TYPO3\CMS\Core\Page\Event\BeforeJavaScriptsRenderingEvent
                method: beforeJavaScriptsRendering

    T3\Min\EventListener\TinysourceEventListener:
        tags:
            -   name: event.listener
                identifier: 'ext-min-tinysource'
                event: TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent
